[project]
name = "SimpleSocialAuthLib"
version = "0.1.0"
description = "Simple Social Auth Library"
authors = [
    {name = "Macktireh", email = "abdimack97@gmail.com"},
]
readme = "README.md"
license = {text = "MIT"}
requires-python = "==3.12.*"
dependencies = [
    "google-api-python-client>=2.143.0",
    "requests-oauthlib>=2.0.0",
]

[tool.pdm.dev-dependencies]
linter = [
    "ruff>=0.6.3",
]


[tool.pdm]
distribution = false
