[project]
name = "SimpleSocialAuthLib"
version = "0.1.0"
description = "Simple Social Auth Library"
authors = [
    {name = "Macktireh", email = "abdimack97@gmail.com"},
]
readme = "README.md"
license = {text = "MIT"}
requires-python = "==3.12.*"
dependencies = []


[tool.pdm]
distribution = false
