[project]
name = "flask_app"
version = "0.1.0"
description = "Demonstration of SimpleSocialAuthLib usage with Flask."
authors = [
    {name = "Macktireh", email = "abdimack97@gmail.com"},
]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.1",
    "python-dotenv>=1.1.1",
    "SimpleSocialAuthLib @ file:///${PROJECT_ROOT}/../..",
]

[tool.pdm]
distribution = false

[tool.pdm.scripts]
dev = "python app.py"
