name: CI

on:
  push:
    branches: ["develop", "main"]
  pull_request:
    branches: ["develop", "main"]

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pdm install -dG lint
      - name: Run ruff
        run: pdm run ruff check --diff

  testing:
    name: Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pdm install -dG test

      - name: Run tests and build coverage file
        run: |
          export PYTHONPATH=src
          export GEMINI_API_KEY=test
          pdm run pytest -v \
          --junitxml=junit.xml -o junit_family=legacy \
          --cov-report=term-missing \
          --cov-report=xml \
          --cov=src -v | tee pytest-coverage.txt

      - name: Pytest coverage comment
        if: github.event_name == 'pull_request'
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./junit.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Macktireh/SimpleSocialAuthLib
