name: Release

on:
  release:
    types: [published]

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
      - name: Publish package distributions to PyPI
        run: |
          pdm publish --password ${{ secrets.PYPI_API_TOKEN }}
